### ISSUE TITLE
CLA link is wrong

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-admin#11]
https://github.com/oslc-op/admin/blob/master/CONTRIBUTING.md links to the CLA gist on GH, while I expect it to lead to an OASIS webpage.

**Comment by berezovskyi** [comment]
@chet-ensign

**Comment by berezovskyi** [comment]
I dug up https://www.oasis-open.org/resources/projects/cla/projects-individual-cla and https://www.oasis-open.org/resources/projects/cla/projects-entity-cla which are password-protected at the moment.

**Comment by OASIS-OP-Admin** [comment]
I will remove the link. What we're referring to there is the CLA Assistant that will check when someone issues a pull request and give them a link to sign that CLA if they have not already done so. The Maintainer will also see on the pull request that the person doesn't have a CLA on file. 
Jory Burson can give more details if you want. jory.burson@oasis-open.org

**Comment by berezovskyi** [comment]
Ah, I see. Thank you!

--
/Andrew
(from phone)



On Mon, May 20, 2019 at 11:45 PM +0200, "OASIS-OP-Admin" <notifications@github.com<mailto:notifications@github.com>> wrote:


I will remove the link. What we're referring to there is the CLA Assistant that will check when someone issues a pull request and give them a link to sign that CLA if they have not already done so. The Maintainer will also see on the pull request that the person doesn't have a CLA on file.
Jory Burson can give more details if you want. jory.burson@oasis-open.org<mailto:jory.burson@oasis-open.org>

**Comment by berezovskyi** [comment]
> CLA Assistant that will check when someone issues a pull request

it does, closing
