### ISSUE TITLE
Prepare an announcement on the open-services.net

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-admin#14]
@oslc-op/pgb needs to prepare a statement about a transition under https://open-services.net/news/

Furthermore, I suggest preparing a shorter version to be sent in an email to all mailing lists where we were active for the last few years in discussing OSLC.

**Comment by berezovskyi** [comment]
Here are my two old drafts:

* News announcement: https://hackmd.io/xW5Nr5MlRVu16I88zcHWbw
* Email announcement: https://hackmd.io/IgBDBsHvTSi8X4IEzAxfcg

@oslc-op/pgb please help me shape these announcements till we have our next PGB meeting.

**Comment by axelreichwein** [comment]
Looks good to me. Thanks for preparing these drafts Andrew! In the Email announcement, you mention that you will have a January 30 meeting on Lyo. Please just change the sentence to past tense. Thanks.

**Comment by berezovskyi** [comment]
@chet-ensign do you have the proposed draft for the announcement post? Or should we take these drafts / my previous email as an initial draft?

**Comment by OASIS-OP-Admin** [comment]
Andrew & all - please have a look at the attached draft I put together from the two announcements. Feel free to tone it down if it comes across as too 'salesy.'

[oslc-announcement.txt](https://github.com/oslc-op/oslc-admin/files/3341048/oslc-announcement.txt)

**Comment by axelreichwein** [comment]
This is very good! Thanks Andrew!

**Comment by jamsden** [comment]
I would recommend adding an additional value proposition. The OSLC OP also allows open project contribution beyond just OASIS specifications. It also allows reference implementations, test suites, samples and other open source content that can help guide the development, verification and use of these specifications by grounding them in the reality of real implementations.

**Comment by OASIS-OP-Admin** [comment]
[oslc-announcement-draft2.txt](https://github.com/oslc-op/oslc-admin/files/3346431/oslc-announcement-draft2.txt)
Thanks Jim - attached is a revised version that adds your language.

**Comment by berezovskyi** [comment]
Looks great to me too!

**Comment by OASIS-OP-Admin** [comment]
Is there anything I need to do with the draft? Can you use it as is?

**Comment by berezovskyi** [comment]
@jamsden I will publish the news post this week. Could you please edit Chet's draft directly and upload it back here?

**Comment by jamsden** [comment]
Looks good.

**Comment by berezovskyi** [comment]
It's live https://open-services.net/news/

Something for a pro LinkedIn member, @axelreichwein ;)
