### ISSUE TITLE
Simplified TSC voting procedure ballot

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/oslc-admin#15]
**Ballot title**
Simplified TSC voting procedure ballot

**Ballot question**
Do you agree to simplify the voting procedure of the TSC in the following way: the ballot is opened in the `#op-tsc` Slack channel and open for 7 days or until all TSC member have cast their votes.

**Ballot opens**
17:45:05 UTC Thursday, 23 May 2019

**Ballot closes**
17:45:05 UTC Thursday, 30 May 2019

|Voter      |abstain|no|yes|comments |
|-----------|-------|--|---|---------|
|Andrii Berezovskyi|       |  |   |         |
|Axel Reichwein|       |  |   |         |
|Jim Amsden|       |  |   |         |

**Final results**
*the chair should state the final results of the ballot here and then close the issue*

@oslc-op/tsc, please cast your vote either by leaving a "+1"/"-1" comment (you can reply to this via email) or leaving a thumbs up / thumbs down reaction. The voting results will be posted here after the ballot closes.

**Comment by berezovskyi** [comment]
I must say doing this on GH is not so bad, actually. And if we use reactions and lock the issue, this may actually be quite a good way to preserve the results (except for the mailing list, of course). On the other hand, allowing ballots both here and on Slack may cause confusion. Then we need to announce every ballot on the 'tsc' mailing list.

**Comment by berezovskyi** [comment]
Ballot did not pass, @oslc-op/tsc.

**Comment by berezovskyi** [comment]
@jamsden @axelreichwein did you get a notification about this one?

**Comment by jamsden** [comment]
I don't remember seeing this.

**Comment by axelreichwein** [comment]
I also don't remember seeing this. I would prefer keepting track of votes on GitHub as the free version of Slack will not persist the channel information forever.

**Comment by berezovskyi** [comment]
True!

--
/Andrew
(from phone)



On Tue, Jun 18, 2019 at 6:58 PM +0200, "Axel Reichwein" <notifications@github.com<mailto:notifications@github.com>> wrote:


I also don't remember seeing this. I would prefer keepting track of votes on GitHub as the free version of Slack will not persist the channel information forever.
