### ISSUE TITLE
OSLC-admin official ballot

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-admin#20]
**Ballot title**
Incorporating open-services.net site maintenance into oslc-op.

**Ballot question** 
Should we migrate the site sources under oslc-op/oslc-website?

**Description** 
The oslc-op PGB has already decided to act as the governing body for open-services.net. So it makes sense to migrate the https://github.com/OSLC/oslc-site-hugo from the GitHub external OSLC organization to the https://github.com/oslc-op organization.

**References** 

**Ballot opens**
1 July 2019, 13:56 EDT

**Ballot closes** 
8 July 2019, 12:00 EDT

|Voter      |abstain|no|yes|comments |
|-----------|-------|--|---|---------|
|Jory Burson|       |  |   |         |
|Chet Ensign|       |  |   |         |
|Carol Geyer|       |  |   |         |
| Bill Chown |       |  |   |         |
| Andrii Berezovskyi |       |  |   |         |
| Akel Reichwein |       |  |   |         |
| Jm Amsden |       |  |   |         |
| Wesley Coelho |       |  |   |         |

**Final results** *the chair should state the final results of the ballot here and then close the issue*

**Comment by berezovskyi** [comment]
Just for the record, I have already cast my vote on the mailing list. Also, I think the table includes more people than there are on the @oslc-op/pgb.

**Comment by OASIS-OP-Admin** [comment]
Yes - Jory, Carol, and I shouldn't be voting. But thank you for offering us the chance.

**Comment by berezovskyi** [comment]
invalid ballot
