### ISSUE TITLE
Submit QM Project Specification Revision 01 for public review

### ISSUE THREAD

**Issue by jamsden** [oslc-op/oslc-admin#8]
This will be the first specification we take through the new Open Project voting, publishing and public review process.

Let's do the votes for this using electronic voting to get that process tested.

**Comment by OASIS-OP-Admin** [comment]
Jim, I'm looking at a solution to the balloting process. I'll update the ticket with my proposal by next Wednesday.

**Comment by berezovskyi** [comment]
@jamsden Please submit it for PGB review when ready. As a co-chair, you can simply open a ballot here as an issue and email the PGB list. See https://www.oasis-open.org/policies-guidelines/open-projects-process#project-specifications-drafts

**Comment by jamsden** [comment]
We will follow the lifecycle contribution -> PSD(PGB vote) -> PS(PGB SMV) -> COS(PRB SMV+3 statements of use) -> OS(upon successful public review an call for consent)

We should submit all the OSLC PS to COS for public review, regardless of their previous status.

**Comment by berezovskyi** [comment]
Sure, but there are two spec releases before the COS and a public review :)

--
/Andrew
(from phone)



On Thu, Jun 27, 2019 at 10:08 PM +0200, "Jim Amsden" <notifications@github.com<mailto:notifications@github.com>> wrote:


We will follow the lifecycle contribution -> PSD(PGB vote) -> PS(PGB SMV) -> COS(PRB SMV+3 statements of use) -> OS(upon successful public review an call for consent)

We should submit all the OSLC PS to COS for public review, regardless of their previous status.
